# DK (Desikan-Killiany) cortical atlas metadata
#
# Spaced region names and lobe assignments for FreeSurfer aparc regions.
# Based on: https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation

dk_metadata <- data.frame(
  region = c(
    "bankssts",
    "caudalanteriorcingulate",
    "caudalmiddlefrontal",
    "corpuscallosum",
    "cuneus",
    "entorhinal",
    "frontalpole",
    "fusiform",
    "inferiorparietal",
    "inferiortemporal",
    "insula",
    "isthmuscingulate",
    "lateraloccipital",
    "lateralorbitofrontal",
    "lingual",
    "medialorbitofrontal",
    "middletemporal",
    "paracentral",
    "parahippocampal",
    "parsopercularis",
    "parsorbitalis",
    "parstriangularis",
    "pericalcarine",
    "postcentral",
    "posteriorcingulate",
    "precentral",
    "precuneus",
    "rostralanteriorcingulate",
    "rostralmiddlefrontal",
    "superiorfrontal",
    "superiorparietal",
    "superiortemporal",
    "supramarginal",
    "temporalpole",
    "transversetemporal"
  ),
  region_pretty = c(
    "banks of superior temporal sulcus",
    "caudal anterior cingulate",
    "caudal middle frontal",
    "corpus callosum",
    "cuneus",
    "entorhinal",
    "frontal pole",
    "fusiform",
    "inferior parietal",
    "inferior temporal",
    "insula",
    "isthmus cingulate",
    "lateral occipital",
    "lateral orbitofrontal",
    "lingual",
    "medial orbitofrontal",
    "middle temporal",
    "paracentral",
    "parahippocampal",
    "pars opercularis",
    "pars orbitalis",
    "pars triangularis",
    "pericalcarine",
    "postcentral",
    "posterior cingulate",
    "precentral",
    "precuneus",
    "rostral anterior cingulate",
    "rostral middle frontal",
    "superior frontal",
    "superior parietal",
    "superior temporal",
    "supramarginal",
    "temporal pole",
    "transverse temporal"
  ),
  lobe = c(
    "temporal",
    "cingulate",
    "frontal",
    "white matter",
    "occipital",
    "temporal",
    "frontal",
    "temporal",
    "parietal",
    "temporal",
    "insula",
    "cingulate",
    "occipital",
    "frontal",
    "occipital",
    "frontal",
    "temporal",
    "frontal",
    "temporal",
    "frontal",
    "frontal",
    "frontal",
    "occipital",
    "parietal",
    "cingulate",
    "frontal",
    "parietal",
    "cingulate",
    "frontal",
    "frontal",
    "parietal",
    "temporal",
    "parietal",
    "temporal",
    "temporal"
  ),
  stringsAsFactors = FALSE
)
